import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ingredienser</h1>
        <ul className="wprm-recipe-ingredients">
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={0}
          >
            <span className="wprm-recipe-ingredient-amount">200</span>{' '}
            <span className="wprm-recipe-ingredient-unit">g</span>{' '}
            <span className="wprm-recipe-ingredient-name">spaghetti</span>{' '}
            <span className="wprm-recipe-ingredient-notes wprm-recipe-ingredient-notes-faded">
              gjerne fullkorn
            </span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={1}
          >
            <span className="wprm-recipe-ingredient-amount">200</span>{' '}
            <span className="wprm-recipe-ingredient-unit">g</span>{' '}
            <span className="wprm-recipe-ingredient-name">
              søte cherrytomater
            </span>{' '}
            <span className="wprm-recipe-ingredient-notes wprm-recipe-ingredient-notes-faded">
              delt i to{' '}
            </span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={2}
          >
            <span className="wprm-recipe-ingredient-amount">1 </span>{' '}
            <span className="wprm-recipe-ingredient-name">rødløk</span>{' '}
            <span className="wprm-recipe-ingredient-notes wprm-recipe-ingredient-notes-faded">
              i halvsirkler
            </span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={3}
          >
            <span className="wprm-recipe-ingredient-amount">3</span>{' '}
            <span className="wprm-recipe-ingredient-name">hvitløksfedd</span>{' '}
            <span className="wprm-recipe-ingredient-notes wprm-recipe-ingredient-notes-faded">
              finhakket
            </span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={4}
          >
            <span className="wprm-recipe-ingredient-amount">100</span>{' '}
            <span className="wprm-recipe-ingredient-unit">g</span>{' '}
            <span className="wprm-recipe-ingredient-name">spinat</span>{' '}
            <span className="wprm-recipe-ingredient-notes wprm-recipe-ingredient-notes-faded">
              grovhakket{' '}
            </span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={5}
          >
            <span className="wprm-recipe-ingredient-amount">1/2</span>{' '}
            <span className="wprm-recipe-ingredient-unit">ts</span>{' '}
            <span className="wprm-recipe-ingredient-name">
              chiliflak / 1/2 chili
            </span>{' '}
            <span className="wprm-recipe-ingredient-notes wprm-recipe-ingredient-notes-faded">
              finhakket
            </span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={6}
          >
            <span className="wprm-recipe-ingredient-amount">1</span>{' '}
            <span className="wprm-recipe-ingredient-unit">ss</span>{' '}
            <span className="wprm-recipe-ingredient-name">balsamicoeddik</span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={7}
          >
            <span className="wprm-recipe-ingredient-amount">1 </span>{' '}
            <span className="wprm-recipe-ingredient-unit">ss</span>{' '}
            <span className="wprm-recipe-ingredient-name">buljongpulver</span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={8}
          >
            <span className="wprm-recipe-ingredient-amount">6</span>{' '}
            <span className="wprm-recipe-ingredient-unit">dl</span>{' '}
            <span className="wprm-recipe-ingredient-name">vann</span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={9}
          >
            <span className="wprm-recipe-ingredient-amount">2</span>{' '}
            <span className="wprm-recipe-ingredient-unit">ss</span>{' '}
            <span className="wprm-recipe-ingredient-name">olivenolje</span>
          </li>
          <li
            className="wprm-recipe-ingredient"
            style={{ listStyleType: 'disc' }}
            data-uid={10}
          >
            <span className="wprm-recipe-ingredient-name">salt og pepper</span>
          </li>
        </ul>
        <h1 className={styles.title}>Valgfri topping</h1>
        <ul>
          <li>2 never valgfri ost revet (valgfritt)</li>
          <li>Frisk basilikum</li>
          <li>
            2 never bønner eller kikerter (valgfritt) min favoritt er
            edamamebønner uten skall fra frysedisken
          </li>
        </ul>
        <h1 className={styles.title}>Fremgangsmåte</h1>
        <ol>
          <li>
            Bruk en vid kjele. Brekk gjerne spagettien i to og ha alle
            ingrediensene, utenom toppingen, i kjelen.
          </li>
          <li>
            Kok under jevnlig omrøring i 8–10 minutter til spagettien er al
            dente og vannet er kokt inn.
          </li>
          <li>Smak til med salt og pepper, og topp med ost og basilikum.</li>
        </ol>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
